[profile.default]
src = "src"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
# polygon = "https://polygon-rpc.com"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
mumbai = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true